### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by Hit1ove** [CrazorTheCat/BSDS-V39#5]
Привет.
Подскажи, на айос где че менять, в файле brawlstars же? Там не могу найти game.brawlstars или че искать для замены на ip сервера?

**Comment by CrazorTheCat** [comment]
Can you ask again but in english please?

**Comment by Hit1ove** [comment]
Hi.
Can you tell me where to change what on the iOS, in the file brawlstars same? There can not find game.brawlstars or what to look for to replace the ip server?
